fix: added another check for component props
DevExpress/testcafe-react-selectors pull request #197
Opened 2023-05-19 17:06 UTC by denisputnov

Closes #196

Please check linked issue to get more information about the problem

---

Required to avoid a TypeError on a subsequent lines for React v18+:

```
TypeError: Cannot read properties of null (reading 'hasOwnProperty')
```

2023-05-19 17:27 UTC, denisputnov commented
AppVeyor build logs looks strange to me

Looks like `node_modules` linting too

2023-05-22 06:22 UTC, denisputnov commented
Hi, @kirovboris!

This is a friendly reminder about the Pull Request and previously opened issue #196.
Your review is required! Please let me know when you check my proposal.

Thank you!

2023-05-25 06:47 UTC, miherlosev requested changes
Hi @denisputnov,

Could you please add a test for the fixed behavior?

2023-05-26 06:31 UTC, kirovboris commented
@denisputnov 
Could you share any details about how you create the target and its parent components?
It doesn't contain props, so it has to be some unhandled component type.

The issues we met before were related to things like portal components, async loading suspense components, tag components, components with empty states, hydrated components, nested root components, etc.
It may help find a good test case.

Also, could you check this issue on 18.0 React or earlier versions? It might help us understand if any new react functionality produces this behavior.

2023-05-26 08:15 UTC, denisputnov commented
Hi @kirovboris,

We are using dynamic imports with build in `import` function and that's all specific functionality.

The issue reproduces on React `18.x.x`, it does not reproduce on lesser versions of React.

I can assume, that the issue is affected by some concurrent rendering features in the React.

2023-05-30 08:50 UTC, merged

2023-05-30 10:05 UTC, kirovboris commented
Published `testcafe-react-selectors@5.0.3`

2023-05-31 06:07 UTC, denisputnov commented
All participated, thank you very much for your help!